version: "3"

services:
#  spider:
#    image: enkito/base:sp500
#    environment:
#      WEBDRIVER_URL: "http://chrome:4444/wd/hub"
#      OUTPUT: "output"
#      DEBUG: "1"
#    command: python3 /usr/src/app/app.py  # 定义启动容器执行的命令
#    depends_on:
#      - chrome
#    links:
#      - chrome
#    volumes:
#      - .:/usr/src/app
#    networks:
#      - default

  chrome:
    restart: always
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"
    networks:
      - default

networks:
  default:
    driver: bridge